### ISSUE TITLE
Widget doesn't appear on artboard, appears in preview and sidebar

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#86] opened 2015-10-05 18:48 UTC
Steps to reproduce:
Add two widgets to editor, add third widget (countdown widget from computer aid) save and preview.

Result:
Preview shows content, editor sidebar shows widget, artboard doesn't show it.

How it should work:
The widget should appear everywhere. 

Link to Presentation:
https://editor.risevision.com/#/editor/workspace/1854a505-8610-4b8a-bf39-d982c3c30b23/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

http://preview.risevision.com/?type=presentation&id=1854a505-8610-4b8a-bf39-d982c3c30b23&showui=false

OS:
Mac Yosemite 10.5

Chrome Ver:
45

![widget-does-not-appear](https://cloud.githubusercontent.com/assets/9273546/10290091/1387d1e4-6b70-11e5-9f0f-5a97defb569f.gif)

**Comment by ezequielc** [comment] 2015-10-06 17:24
@sheadarlison The root cause is the same as issue #88 . It is fixed now. Thanks

**Closed by ezequielc** 2015-10-06 17:24 UTC
