### ISSUE TITLE
In the in-app store of the new editor gadgets show up

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#131] opened 2015-11-05 15:59 UTC
In the editor in-app store unsupported gadgets show up but cannot be added to the presentation and no error message is given to the user letting them know why.

![editor-gadgets-show-up](https://cloud.githubusercontent.com/assets/9273546/10973645/4713bf6a-83ac-11e5-8ad7-2095e4e4e795.gif)

**Comment by ezequielc** [comment] 2015-11-06 18:25
Duplicate of https://github.com/Rise-Vision/editor-app/issues/136

**Closed by ezequielc** 2015-11-06 18:25 UTC
